package codegen

import (
	"bytes"
	"fmt"
	"go/format"
	"io"
	"strconv"
	"unicode"

	"github.com/wow-look-at-my/go-regex-compiler/internal/dfa"
)

// Options controls the generated code.
type Options struct {
	PackageName string // Go package name
	FuncName    string // Name of the generated match function
	Regex       string // Original regex (for comment)
}

// Generate writes Go source code implementing a DFA matcher to w.
func Generate(w io.Writer, d *dfa.DFA, opts Options) error {
	var buf bytes.Buffer

	ascii := isASCIIOnly(d)

	fmt.Fprintf(&buf, "// Code generated by regex-gen. DO NOT EDIT.\n")
	fmt.Fprintf(&buf, "// Source regex: %s\n\n", quoteRegex(opts.Regex))
	fmt.Fprintf(&buf, "package %s\n\n", opts.PackageName)

	if !ascii {
		fmt.Fprintf(&buf, "import \"unicode/utf8\"\n\n")
	}

	writeMatchFunc(&buf, d, opts, ascii)

	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		// If formatting fails, write unformatted so user can debug
		_, werr := w.Write(buf.Bytes())
		if werr != nil {
			return werr
		}
		return fmt.Errorf("formatting generated code: %w", err)
	}

	_, err = w.Write(formatted)
	return err
}

func writeMatchFunc(buf *bytes.Buffer, d *dfa.DFA, opts Options, ascii bool) {
	fmt.Fprintf(buf, "// %s reports whether input fully matches the regex %s.\n",
		opts.FuncName, quoteRegex(opts.Regex))
	fmt.Fprintf(buf, "func %s(input string) bool {\n", opts.FuncName)

	// Handle edge case: no states or no accepting states
	if len(d.States) == 0 {
		fmt.Fprintf(buf, "\treturn false\n")
		fmt.Fprintf(buf, "}\n")
		return
	}

	// Check if the start state is accepting (matches empty string)
	startAccepts := d.States[d.Start].Accept

	// If the DFA has only one state that is accepting with no transitions,
	// the regex matches only the empty string.
	if len(d.States) == 1 && startAccepts && len(d.States[0].Transitions) == 0 {
		fmt.Fprintf(buf, "\treturn len(input) == 0\n")
		fmt.Fprintf(buf, "}\n")
		return
	}

	fmt.Fprintf(buf, "\tstate := %d\n", d.Start)

	if ascii {
		writeASCIILoop(buf, d)
	} else {
		writeUTF8Loop(buf, d)
	}

	// Write accepting state check
	writeAcceptCheck(buf, d)

	fmt.Fprintf(buf, "}\n")
}

func writeASCIILoop(buf *bytes.Buffer, d *dfa.DFA) {
	fmt.Fprintf(buf, "\tfor i := 0; i < len(input); i++ {\n")
	fmt.Fprintf(buf, "\t\tc := input[i]\n")
	fmt.Fprintf(buf, "\t\tswitch state {\n")

	for _, state := range d.States {
		if len(state.Transitions) == 0 && !state.Accept {
			continue // dead state, will be caught by default
		}
		fmt.Fprintf(buf, "\t\tcase %d:\n", state.ID)
		fmt.Fprintf(buf, "\t\t\tswitch {\n")
		for _, tr := range state.Transitions {
			writeByteCondition(buf, tr)
			fmt.Fprintf(buf, "\t\t\t\tstate = %d\n", tr.Next)
		}
		fmt.Fprintf(buf, "\t\t\tdefault:\n")
		fmt.Fprintf(buf, "\t\t\t\treturn false\n")
		fmt.Fprintf(buf, "\t\t\t}\n")
	}

	fmt.Fprintf(buf, "\t\tdefault:\n")
	fmt.Fprintf(buf, "\t\t\treturn false\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t}\n")
}

func writeUTF8Loop(buf *bytes.Buffer, d *dfa.DFA) {
	fmt.Fprintf(buf, "\tfor i := 0; i < len(input); {\n")
	fmt.Fprintf(buf, "\t\tr, size := utf8.DecodeRuneInString(input[i:])\n")
	fmt.Fprintf(buf, "\t\tif r == utf8.RuneError && size == 1 {\n")
	fmt.Fprintf(buf, "\t\t\treturn false\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\tswitch state {\n")

	for _, state := range d.States {
		if len(state.Transitions) == 0 && !state.Accept {
			continue
		}
		fmt.Fprintf(buf, "\t\tcase %d:\n", state.ID)
		fmt.Fprintf(buf, "\t\t\tswitch {\n")
		for _, tr := range state.Transitions {
			writeRuneCondition(buf, tr)
			fmt.Fprintf(buf, "\t\t\t\tstate = %d\n", tr.Next)
		}
		fmt.Fprintf(buf, "\t\t\tdefault:\n")
		fmt.Fprintf(buf, "\t\t\t\treturn false\n")
		fmt.Fprintf(buf, "\t\t\t}\n")
	}

	fmt.Fprintf(buf, "\t\tdefault:\n")
	fmt.Fprintf(buf, "\t\t\treturn false\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\ti += size\n")
	fmt.Fprintf(buf, "\t}\n")
}

func writeAcceptCheck(buf *bytes.Buffer, d *dfa.DFA) {
	var acceptingStates []int
	for _, s := range d.States {
		if s.Accept {
			acceptingStates = append(acceptingStates, s.ID)
		}
	}

	if len(acceptingStates) == 0 {
		fmt.Fprintf(buf, "\treturn false\n")
		return
	}

	if len(acceptingStates) == 1 {
		fmt.Fprintf(buf, "\treturn state == %d\n", acceptingStates[0])
		return
	}

	fmt.Fprintf(buf, "\tswitch state {\n")
	fmt.Fprintf(buf, "\tcase ")
	for i, id := range acceptingStates {
		if i > 0 {
			fmt.Fprintf(buf, ", ")
		}
		fmt.Fprintf(buf, "%d", id)
	}
	fmt.Fprintf(buf, ":\n")
	fmt.Fprintf(buf, "\t\treturn true\n")
	fmt.Fprintf(buf, "\tdefault:\n")
	fmt.Fprintf(buf, "\t\treturn false\n")
	fmt.Fprintf(buf, "\t}\n")
}

func writeByteCondition(buf *bytes.Buffer, tr dfa.Transition) {
	if tr.Lo == tr.Hi {
		fmt.Fprintf(buf, "\t\t\tcase c == %s:\n", quoteByte(byte(tr.Lo)))
	} else {
		fmt.Fprintf(buf, "\t\t\tcase c >= %s && c <= %s:\n", quoteByte(byte(tr.Lo)), quoteByte(byte(tr.Hi)))
	}
}

func writeRuneCondition(buf *bytes.Buffer, tr dfa.Transition) {
	if tr.Lo == tr.Hi {
		fmt.Fprintf(buf, "\t\t\tcase r == %s:\n", quoteRune(tr.Lo))
	} else {
		fmt.Fprintf(buf, "\t\t\tcase r >= %s && r <= %s:\n", quoteRune(tr.Lo), quoteRune(tr.Hi))
	}
}

func quoteRune(r rune) string {
	return strconv.QuoteRune(r)
}

func quoteByte(b byte) string {
	return strconv.QuoteRune(rune(b))
}

func quoteRegex(s string) string {
	return "`" + s + "`"
}

// isASCIIOnly returns true if all DFA transitions only involve runes <= 127.
func isASCIIOnly(d *dfa.DFA) bool {
	for _, state := range d.States {
		for _, tr := range state.Transitions {
			if tr.Hi > unicode.MaxASCII {
				return false
			}
		}
	}
	return true
}
