package codegen

import (
	"bytes"
	"go/parser"
	"go/token"
	"regexp/syntax"
	"strings"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"github.com/wow-look-at-my/go-regex-compiler/internal/dfa"
)

func buildDFA(t *testing.T, pattern string) *dfa.DFA {
	t.Helper()
	re, err := syntax.Parse(pattern, syntax.Perl)
	require.NoError(t, err)
	re = re.Simplify()
	prog, err := syntax.Compile(re)
	require.NoError(t, err)
	d, err := dfa.Build(prog)
	require.NoError(t, err)
	return d
}

func generateCode(t *testing.T, pattern, pkg, funcName string) string {
	t.Helper()
	d := buildDFA(t, pattern)
	var buf bytes.Buffer
	opts := Options{
		PackageName: pkg,
		FuncName:    funcName,
		Regex:       pattern,
	}
	err := Generate(&buf, d, opts)
	require.NoError(t, err)
	return buf.String()
}

func TestGenerateProducesValidGo(t *testing.T) {
	patterns := []string{
		"abc",
		"[a-z]+",
		"a|b",
		"a*",
		"a+",
		"a?",
		".",
		`\d+`,
		`[A-Za-z_][A-Za-z0-9_]*`,
		"(foo|bar)baz",
		`\d{3}-\d{2}-\d{4}`,
		"",
		`[a-z0-9][a-z0-9._-]{0,127}`,
	}

	for _, pattern := range patterns {
		t.Run(pattern, func(t *testing.T) {
			output := generateCode(t, pattern, "testpkg", "Match")

			fset := token.NewFileSet()
			_, err := parser.ParseFile(fset, "generated.go", output, 0)
			assert.NoError(t, err, "generated code should be valid Go for %q:\n%s", pattern, output)
		})
	}
}

func TestGenerateHeader(t *testing.T) {
	output := generateCode(t, "abc", "mypkg", "MatchABC")

	assert.Contains(t, output, "Code generated by go-regex-compiler. DO NOT EDIT.")
	assert.Contains(t, output, "package mypkg")
	assert.Contains(t, output, "func MatchABC(input string) bool")
	assert.Contains(t, output, "Source regex: `abc`")
}

func TestGenerateASCIIOptimization(t *testing.T) {
	output := generateCode(t, "[a-z]+", "testpkg", "Match")

	assert.NotContains(t, output, "unicode/utf8", "ASCII-only regex should not import unicode/utf8")
	assert.Contains(t, output, "input[i]", "ASCII-only regex should use byte-level indexing")
}

func TestGenerateUnicodeUsesUTF8(t *testing.T) {
	output := generateCode(t, `[\x{00C0}-\x{00FF}]+`, "testpkg", "Match")

	assert.Contains(t, output, "unicode/utf8")
	assert.Contains(t, output, "utf8.DecodeRuneInString")
}

func TestGenerateEmptyRegex(t *testing.T) {
	output := generateCode(t, "", "testpkg", "Match")

	fset := token.NewFileSet()
	_, err := parser.ParseFile(fset, "generated.go", output, 0)
	assert.NoError(t, err, "generated code for empty regex should be valid Go:\n%s", output)
}

func TestIsASCIIOnly(t *testing.T) {
	asciiDFA := buildDFA(t, "[a-z]+")
	assert.True(t, isASCIIOnly(asciiDFA))

	unicodeDFA := buildDFA(t, `[\x{00C0}-\x{00FF}]+`)
	assert.False(t, isASCIIOnly(unicodeDFA))
}

func TestGenerateFuncName(t *testing.T) {
	tests := []struct {
		funcName string
		pattern  string
	}{
		{"MatchEmail", `[a-z]+@[a-z]+\.[a-z]+`},
		{"IsValid", `[0-9]+`},
		{"CheckHex", `#[0-9a-f]+`},
	}

	for _, tt := range tests {
		t.Run(tt.funcName, func(t *testing.T) {
			output := generateCode(t, tt.pattern, "pkg", tt.funcName)
			assert.Contains(t, output, "func "+tt.funcName+"(input string) bool")
		})
	}
}

func TestGeneratePackageName(t *testing.T) {
	for _, pkg := range []string{"main", "mypkg", "validators"} {
		t.Run(pkg, func(t *testing.T) {
			output := generateCode(t, "abc", pkg, "Match")
			assert.True(t, strings.Contains(output, "package "+pkg+"\n") || strings.Contains(output, "package "+pkg+"\r\n"))
		})
	}
}

func generateWithMode(t *testing.T, pattern, funcName string, mode MatchMode) string {
	t.Helper()
	d := buildDFA(t, pattern)
	var buf bytes.Buffer
	opts := Options{
		PackageName: "testpkg",
		FuncName:    funcName,
		Regex:       pattern,
		Mode:        mode,
	}
	err := Generate(&buf, d, opts)
	require.NoError(t, err)
	return buf.String()
}

func assertValidGo(t *testing.T, code string) {
	t.Helper()
	fset := token.NewFileSet()
	_, err := parser.ParseFile(fset, "generated.go", code, 0)
	assert.NoError(t, err, "generated code should be valid Go:\n%s", code)
}

func TestGeneratePrefixMode(t *testing.T) {
	patterns := []string{"abc", "[a-z]+", `\d{3}-\d{2}`, "a+b", ""}
	for _, p := range patterns {
		t.Run(p, func(t *testing.T) {
			output := generateWithMode(t, p, "MatchPrefix", MatchPrefix)
			assertValidGo(t, output)
			assert.Contains(t, output, "func MatchPrefix(input string) bool")
			assert.Contains(t, output, "reports whether a prefix of input matches")
		})
	}
}

func TestGenerateContainsMode(t *testing.T) {
	patterns := []string{"abc", "[a-z]+", `\d{3}`, "error", ""}
	for _, p := range patterns {
		t.Run(p, func(t *testing.T) {
			output := generateWithMode(t, p, "MatchContains", MatchContains)
			assertValidGo(t, output)
			assert.Contains(t, output, "func MatchContains(input string) bool")
			assert.Contains(t, output, "reports whether any substring of input matches")
		})
	}
}

func TestGeneratePrefixModeUnicode(t *testing.T) {
	output := generateWithMode(t, `[\x{00C0}-\x{00FF}]+`, "MatchPrefix", MatchPrefix)
	assertValidGo(t, output)
	assert.Contains(t, output, "utf8.DecodeRuneInString")
	assert.Contains(t, output, "goto done")
}

func TestGenerateContainsModeUnicode(t *testing.T) {
	output := generateWithMode(t, `[\x{00C0}-\x{00FF}]+`, "MatchContains", MatchContains)
	assertValidGo(t, output)
	assert.Contains(t, output, "utf8.DecodeRuneInString")
}

func TestGenerateSubmatch(t *testing.T) {
	patterns := []struct {
		name    string
		pattern string
	}{
		{"simple_groups", `([a-z]+)@([a-z]+)`},
		{"ssn", `(\d{3})-(\d{2})-(\d{4})`},
		{"alternation", `(foo|bar)baz`},
		{"repeated_group", `([a-z]+)(\.[a-z]+)*`},
		{"single_group", `(a+)(b+)`},
	}

	for _, tt := range patterns {
		t.Run(tt.name, func(t *testing.T) {
			re, err := syntax.Parse(tt.pattern, syntax.Perl)
			require.NoError(t, err)
			re = re.Simplify()
			prog, err := syntax.Compile(re)
			require.NoError(t, err)
			d, err := dfa.Build(prog)
			require.NoError(t, err)

			numGroups := countGroups(re)

			var buf bytes.Buffer
			opts := Options{
				PackageName: "testpkg",
				FuncName:    "Match",
				Regex:       tt.pattern,
				Submatch: &SubmatchOptions{
					FuncName:  "FindSubmatch",
					MatchFunc: "Match",
					Regex:     tt.pattern,
					Prog:      prog,
					NumGroups: numGroups,
				},
			}
			err = Generate(&buf, d, opts)
			require.NoError(t, err)

			output := buf.String()
			assertValidGo(t, output)
			assert.Contains(t, output, "func FindSubmatch(input string) []string")
			assert.Contains(t, output, "opRune")
			assert.Contains(t, output, "addThread")
			assert.Contains(t, output, "RuneMatch")
			// The NFA program + instruction type are hoisted to package scope,
			// uniquely named per matcher, and built once (no per-call rebuild).
			assert.Contains(t, output, "type findSubmatchIndexInst struct")
			assert.Contains(t, output, "var findSubmatchIndexProg = []findSubmatchIndexInst{")
			assert.Contains(t, output, "sync.Pool")
			// The per-position map is gone: no map allocation in the hot path.
			assert.NotContains(t, output, "make(map[int]bool)")
		})
	}
}

// generateNamedSubmatch builds a full submatch family (positional, index,
// names, optional struct) for a pattern and returns the generated source.
func generateNamedSubmatch(t *testing.T, pattern string, withStruct bool) string {
	t.Helper()
	re, err := syntax.Parse(pattern, syntax.Perl)
	require.NoError(t, err)
	names := make([]string, countGroups(re)+1)
	collectNames(re, names)
	re2 := re.Simplify()
	prog, err := syntax.Compile(re2)
	require.NoError(t, err)
	d, err := dfa.Build(prog)
	require.NoError(t, err)

	sub := &SubmatchOptions{
		FuncName:      "FindSub",
		MatchFunc:     "Match",
		Regex:         pattern,
		Prog:          prog,
		NumGroups:     countGroups(re),
		GroupNames:    names,
		NamesFuncName: "SubexpNames",
	}
	if withStruct {
		sub.StructEnabled = true
		sub.StructType = "Captures"
		sub.StructFunc = "FindCaptures"
	}
	var buf bytes.Buffer
	require.NoError(t, Generate(&buf, d, Options{
		PackageName: "testpkg",
		FuncName:    "Match",
		Regex:       pattern,
		Submatch:    sub,
	}))
	return buf.String()
}

func collectNames(re *syntax.Regexp, names []string) {
	if re.Op == syntax.OpCapture && re.Cap >= 0 && re.Cap < len(names) {
		names[re.Cap] = re.Name
	}
	for _, sub := range re.Sub {
		collectNames(sub, names)
	}
}

func TestGenerateNamedSubmatchEmitsFamily(t *testing.T) {
	out := generateNamedSubmatch(t, `(?P<year>\d{4})-(?P<month>\d{2})`, true)
	assertValidGo(t, out)

	// Core index function + positional wrapper + names accessor.
	assert.Contains(t, out, "func FindSubIndex(input string) []int")
	assert.Contains(t, out, "func FindSub(input string) []string")
	assert.Contains(t, out, "func SubexpNames() []string")
	assert.Contains(t, out, `return []string{"", "year", "month"}`)

	// Typed struct + constructor with exported fields.
	assert.Contains(t, out, "type Captures struct")
	assert.Contains(t, out, "Year string")
	assert.Contains(t, out, "Month string")
	assert.Contains(t, out, "Matched bool")
	assert.Contains(t, out, "func FindCaptures(input string) Captures")

	// Empty-width assertion machinery is present in the core.
	assert.Contains(t, out, "EmptyOpsAt")
	assert.Contains(t, out, "EmptyWordBoundary")
}

func TestGenerateUnnamedSubmatchNoStructMachinery(t *testing.T) {
	// A pattern with NO named groups must not emit struct/constructor machinery
	// even with the struct enabled (HasNamedGroups gate), and must have no
	// unused imports.
	out := generateNamedSubmatch(t, `(\d{4})-(\d{2})`, true)
	assertValidGo(t, out)

	assert.NotContains(t, out, "type Captures struct")
	assert.NotContains(t, out, "func FindCaptures")
	// Names accessor is still emitted (all entries empty).
	assert.Contains(t, out, "func SubexpNames() []string")
	assert.Contains(t, out, `return []string{"", "", ""}`)

	// No unused imports: this ASCII pattern needs neither unicode/utf8 nor any
	// new package introduced by the submatch additions. Verify the file builds
	// and that go/format does not report an import-related problem by parsing it.
	assertNoUnusedImports(t, out)
}

// assertNoUnusedImports parses the file and checks that every imported package
// (other than blank/dot imports) is referenced, catching a stray import the
// templates might leak.
func assertNoUnusedImports(t *testing.T, code string) {
	t.Helper()
	fset := token.NewFileSet()
	f, err := parser.ParseFile(fset, "generated.go", code, parser.ImportsOnly)
	require.NoError(t, err)
	for _, imp := range f.Imports {
		path := strings.Trim(imp.Path.Value, `"`)
		// Derive the default package identifier (last path element).
		parts := strings.Split(path, "/")
		ident := parts[len(parts)-1]
		if imp.Name != nil {
			ident = imp.Name.Name
		}
		if ident == "_" || ident == "." {
			continue
		}
		assert.Contains(t, code, ident+".", "import %q appears unused in generated code:\n%s", path, code)
	}
}

func TestGenerateSubmatchNamesParity(t *testing.T) {
	// The generated SubexpNames slice literal must list the same names regexp
	// would report (verified structurally; e2e tests verify at runtime).
	out := generateNamedSubmatch(t, `(?P<a>x)(y)(?P<b>z)`, false)
	assertValidGo(t, out)
	assert.Contains(t, out, `return []string{"", "a", "", "b"}`)
}

// countGroups counts capture groups in a parsed regex.
func countGroups(re *syntax.Regexp) int {
	n := 0
	if re.Op == syntax.OpCapture {
		n = 1
	}
	for _, sub := range re.Sub {
		n += countGroups(sub)
	}
	return n
}

func TestInstOpName(t *testing.T) {
	tests := []struct {
		op       syntax.InstOp
		want     string
		wantCode int
	}{
		{syntax.InstRune, "opRune", 0},
		{syntax.InstRune1, "opRune1", 1},
		{syntax.InstRuneAny, "opRuneAny", 2},
		{syntax.InstRuneAnyNotNL, "opRuneAnyNL", 3},
		{syntax.InstAlt, "opAlt", 4},
		{syntax.InstAltMatch, "opAlt", 4},
		{syntax.InstCapture, "opCapture", 5},
		{syntax.InstMatch, "opMatch", 6},
		{syntax.InstNop, "opNop", 7},
		{syntax.InstFail, "opFail", 8},
		{syntax.InstEmptyWidth, "opEmpty", 9},
		{syntax.InstOp(255), "255", 255},
	}
	for _, tt := range tests {
		assert.Equal(t, tt.want, instOpName(tt.op))
		// instOpCode must agree with the numeric op baked into the program table
		// and, for known ops, index the symbolic name emitted in the sim.
		assert.Equal(t, tt.wantCode, instOpCode(tt.op), "op code for %s", tt.want)
	}
}

func TestLowerFirst(t *testing.T) {
	assert.Equal(t, "", lowerFirst(""))
	assert.Equal(t, "findSubIndex", lowerFirst("FindSubIndex"))
	assert.Equal(t, "match", lowerFirst("match"))
	assert.Equal(t, "xMatch", lowerFirst("XMatch"))
}

func TestFormatRunes(t *testing.T) {
	assert.Equal(t, "[]rune{97}", formatRunes([]rune{'a'}))
	assert.Equal(t, "[]rune{97, 122}", formatRunes([]rune{'a', 'z'}))
	assert.Equal(t, "[]rune{48, 57, 65, 90}", formatRunes([]rune{'0', '9', 'A', 'Z'}))
}

func TestBuildSubmatchContext(t *testing.T) {
	re, err := syntax.Parse(`([a-z]+)@([a-z]+)`, syntax.Perl)
	require.NoError(t, err)
	re = re.Simplify()
	prog, err := syntax.Compile(re)
	require.NoError(t, err)

	ctx := buildSubmatchContext(SubmatchOptions{
		FuncName:  "FindSubmatch",
		MatchFunc: "Match",
		Regex:     `([a-z]+)@([a-z]+)`,
		Prog:      prog,
		NumGroups: 2,
	})

	assert.Equal(t, "FindSubmatch", ctx.FuncName)
	assert.Equal(t, "Match", ctx.MatchFunc)
	assert.Equal(t, 6, ctx.NumSlots)  // (2+1)*2
	assert.Equal(t, 3, ctx.NumGroups) // 6/2
	assert.Equal(t, prog.Start, ctx.StartPC)
	assert.Equal(t, len(prog.Inst), len(ctx.Instructions))

	// Verify at least one instruction has runes
	hasRunes := false
	for _, inst := range ctx.Instructions {
		if inst.Runes != "" {
			hasRunes = true
			break
		}
	}
	assert.True(t, hasRunes, "expected at least one instruction with runes")
}

func TestGenerateChainCompression(t *testing.T) {
	output := generateCode(t, `[a-z0-9][a-z0-9._-]{0,127}`, "testpkg", "Match")
	assertValidGo(t, output)

	assert.Contains(t, output, "chainCount0")

	lines := strings.Count(output, "\n")
	assert.Less(t, lines, 200, "generated code should be compact with chain compression, got %d lines", lines)
}

func TestGenerateEmptyStates(t *testing.T) {
	// DFA with no states at all
	d := &dfa.DFA{States: nil, Start: 0}
	var buf bytes.Buffer
	err := Generate(&buf, d, Options{
		PackageName: "testpkg",
		FuncName:    "Match",
		Regex:       "impossible",
	})
	require.NoError(t, err)
	output := buf.String()
	assertValidGo(t, output)
	assert.Contains(t, output, "return false")
}
