package codegen

import (
	"bytes"
	"go/parser"
	"go/token"
	"regexp/syntax"
	"strings"
	"testing"

	"github.com/wow-look-at-my/go-regex-compiler/internal/dfa"
)

func buildDFA(t *testing.T, pattern string) *dfa.DFA {
	t.Helper()
	re, err := syntax.Parse(pattern, syntax.Perl)
	if err != nil {
		t.Fatalf("syntax.Parse(%q): %v", pattern, err)
	}
	re = re.Simplify()
	prog, err := syntax.Compile(re)
	if err != nil {
		t.Fatalf("syntax.Compile(%q): %v", pattern, err)
	}
	d, err := dfa.Build(prog)
	if err != nil {
		t.Fatalf("dfa.Build(%q): %v", pattern, err)
	}
	return d
}

func TestGenerateProducesValidGo(t *testing.T) {
	patterns := []string{
		"abc",
		"[a-z]+",
		"a|b",
		"a*",
		"a+",
		"a?",
		".",
		`\d+`,
		`[A-Za-z_][A-Za-z0-9_]*`,
		"(foo|bar)baz",
		`\d{3}-\d{2}-\d{4}`,
		"",
	}

	for _, pattern := range patterns {
		t.Run(pattern, func(t *testing.T) {
			d := buildDFA(t, pattern)
			var buf bytes.Buffer
			opts := Options{
				PackageName: "testpkg",
				FuncName:    "Match",
				Regex:       pattern,
			}
			err := Generate(&buf, d, opts)
			if err != nil {
				t.Fatalf("Generate(%q): %v", pattern, err)
			}

			// Verify it's valid Go
			fset := token.NewFileSet()
			_, err = parser.ParseFile(fset, "generated.go", buf.Bytes(), 0)
			if err != nil {
				t.Errorf("generated code is not valid Go for %q: %v\n%s", pattern, err, buf.String())
			}
		})
	}
}

func TestGenerateHeader(t *testing.T) {
	d := buildDFA(t, "abc")
	var buf bytes.Buffer
	opts := Options{
		PackageName: "mypkg",
		FuncName:    "MatchABC",
		Regex:       "abc",
	}
	err := Generate(&buf, d, opts)
	if err != nil {
		t.Fatal(err)
	}

	output := buf.String()
	if !strings.Contains(output, "Code generated by regex-gen. DO NOT EDIT.") {
		t.Error("missing generated code header")
	}
	if !strings.Contains(output, "package mypkg") {
		t.Error("missing package declaration")
	}
	if !strings.Contains(output, "func MatchABC(input string) bool") {
		t.Error("missing function declaration")
	}
	if !strings.Contains(output, "Source regex: `abc`") {
		t.Error("missing source regex comment")
	}
}

func TestGenerateASCIIOptimization(t *testing.T) {
	// ASCII-only regex should use byte-level indexing
	d := buildDFA(t, "[a-z]+")
	var buf bytes.Buffer
	opts := Options{
		PackageName: "testpkg",
		FuncName:    "Match",
		Regex:       "[a-z]+",
	}
	err := Generate(&buf, d, opts)
	if err != nil {
		t.Fatal(err)
	}

	output := buf.String()
	// Should NOT import unicode/utf8 for ASCII-only patterns
	if strings.Contains(output, "unicode/utf8") {
		t.Error("ASCII-only regex should not import unicode/utf8")
	}
	// Should use byte-level indexing
	if !strings.Contains(output, "input[i]") {
		t.Error("ASCII-only regex should use byte-level indexing")
	}
}

func TestGenerateUnicodeUsesUTF8(t *testing.T) {
	// Unicode regex should use utf8.DecodeRuneInString
	d := buildDFA(t, `[\x{00C0}-\x{00FF}]+`)
	var buf bytes.Buffer
	opts := Options{
		PackageName: "testpkg",
		FuncName:    "Match",
		Regex:       `[\x{00C0}-\x{00FF}]+`,
	}
	err := Generate(&buf, d, opts)
	if err != nil {
		t.Fatal(err)
	}

	output := buf.String()
	if !strings.Contains(output, "unicode/utf8") {
		t.Error("Unicode regex should import unicode/utf8")
	}
	if !strings.Contains(output, "utf8.DecodeRuneInString") {
		t.Error("Unicode regex should use utf8.DecodeRuneInString")
	}
}

func TestGenerateEmptyRegex(t *testing.T) {
	d := buildDFA(t, "")
	var buf bytes.Buffer
	opts := Options{
		PackageName: "testpkg",
		FuncName:    "Match",
		Regex:       "",
	}
	err := Generate(&buf, d, opts)
	if err != nil {
		t.Fatal(err)
	}

	output := buf.String()
	// Should produce valid Go that matches only empty string
	fset := token.NewFileSet()
	_, err = parser.ParseFile(fset, "generated.go", []byte(output), 0)
	if err != nil {
		t.Errorf("generated code for empty regex is not valid Go: %v\n%s", err, output)
	}
}
