package codegen

import (
	"bytes"
	"go/parser"
	"go/token"
	"regexp/syntax"
	"strings"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"github.com/wow-look-at-my/go-regex-compiler/internal/dfa"
)

func buildDFA(t *testing.T, pattern string) *dfa.DFA {
	t.Helper()
	re, err := syntax.Parse(pattern, syntax.Perl)
	require.NoError(t, err)
	re = re.Simplify()
	prog, err := syntax.Compile(re)
	require.NoError(t, err)
	d, err := dfa.Build(prog)
	require.NoError(t, err)
	return d
}

func generateCode(t *testing.T, pattern, pkg, funcName string) string {
	t.Helper()
	d := buildDFA(t, pattern)
	var buf bytes.Buffer
	opts := Options{
		PackageName: pkg,
		FuncName:    funcName,
		Regex:       pattern,
	}
	err := Generate(&buf, d, opts)
	require.NoError(t, err)
	return buf.String()
}

func TestGenerateProducesValidGo(t *testing.T) {
	patterns := []string{
		"abc",
		"[a-z]+",
		"a|b",
		"a*",
		"a+",
		"a?",
		".",
		`\d+`,
		`[A-Za-z_][A-Za-z0-9_]*`,
		"(foo|bar)baz",
		`\d{3}-\d{2}-\d{4}`,
		"",
	}

	for _, pattern := range patterns {
		t.Run(pattern, func(t *testing.T) {
			output := generateCode(t, pattern, "testpkg", "Match")

			fset := token.NewFileSet()
			_, err := parser.ParseFile(fset, "generated.go", output, 0)
			assert.NoError(t, err, "generated code should be valid Go for %q:\n%s", pattern, output)
		})
	}
}

func TestGenerateHeader(t *testing.T) {
	output := generateCode(t, "abc", "mypkg", "MatchABC")

	assert.Contains(t, output, "Code generated by regex-gen. DO NOT EDIT.")
	assert.Contains(t, output, "package mypkg")
	assert.Contains(t, output, "func MatchABC(input string) bool")
	assert.Contains(t, output, "Source regex: `abc`")
}

func TestGenerateASCIIOptimization(t *testing.T) {
	output := generateCode(t, "[a-z]+", "testpkg", "Match")

	assert.NotContains(t, output, "unicode/utf8", "ASCII-only regex should not import unicode/utf8")
	assert.Contains(t, output, "input[i]", "ASCII-only regex should use byte-level indexing")
}

func TestGenerateUnicodeUsesUTF8(t *testing.T) {
	output := generateCode(t, `[\x{00C0}-\x{00FF}]+`, "testpkg", "Match")

	assert.Contains(t, output, "unicode/utf8")
	assert.Contains(t, output, "utf8.DecodeRuneInString")
}

func TestGenerateEmptyRegex(t *testing.T) {
	output := generateCode(t, "", "testpkg", "Match")

	fset := token.NewFileSet()
	_, err := parser.ParseFile(fset, "generated.go", output, 0)
	assert.NoError(t, err, "generated code for empty regex should be valid Go:\n%s", output)
}

func TestIsASCIIOnly(t *testing.T) {
	asciiDFA := buildDFA(t, "[a-z]+")
	assert.True(t, isASCIIOnly(asciiDFA))

	unicodeDFA := buildDFA(t, `[\x{00C0}-\x{00FF}]+`)
	assert.False(t, isASCIIOnly(unicodeDFA))
}

func TestGenerateFuncName(t *testing.T) {
	tests := []struct {
		funcName string
		pattern  string
	}{
		{"MatchEmail", `[a-z]+@[a-z]+\.[a-z]+`},
		{"IsValid", `[0-9]+`},
		{"CheckHex", `#[0-9a-f]+`},
	}

	for _, tt := range tests {
		t.Run(tt.funcName, func(t *testing.T) {
			output := generateCode(t, tt.pattern, "pkg", tt.funcName)
			assert.Contains(t, output, "func "+tt.funcName+"(input string) bool")
		})
	}
}

func TestGeneratePackageName(t *testing.T) {
	for _, pkg := range []string{"main", "mypkg", "validators"} {
		t.Run(pkg, func(t *testing.T) {
			output := generateCode(t, "abc", pkg, "Match")
			assert.True(t, strings.Contains(output, "package "+pkg+"\n") || strings.Contains(output, "package "+pkg+"\r\n"))
		})
	}
}
