package codegen

import (
	"bytes"
	"fmt"
	"go/format"
	"io"
	"strconv"
	"unicode"

	"github.com/wow-look-at-my/go-regex-compiler/internal/dfa"
)

// MatchMode controls how the generated function matches input.
type MatchMode int

const (
	// MatchFull requires the entire input to match (default). Equivalent to ^pattern$.
	MatchFull MatchMode = iota
	// MatchPrefix matches if a prefix of the input matches the pattern. Equivalent to ^pattern.
	MatchPrefix
	// MatchContains matches if any substring of the input matches. Equivalent to unanchored pattern.
	MatchContains
)

// Options controls the generated code.
type Options struct {
	PackageName string    // Go package name
	FuncName    string    // Name of the generated match function
	Regex       string    // Original regex (for comment)
	Mode        MatchMode // Match mode (default: MatchFull)
	Submatch    *SubmatchOptions // If non-nil, also generate a FindSubmatch function
}

// Generate writes Go source code implementing a DFA matcher to w.
func Generate(w io.Writer, d *dfa.DFA, opts Options) error {
	var buf bytes.Buffer

	ascii := isASCIIOnly(d)

	fmt.Fprintf(&buf, "// Code generated by regex-gen. DO NOT EDIT.\n")
	fmt.Fprintf(&buf, "// Source regex: %s\n\n", quoteRegex(opts.Regex))
	fmt.Fprintf(&buf, "package %s\n\n", opts.PackageName)

	if !ascii {
		fmt.Fprintf(&buf, "import \"unicode/utf8\"\n\n")
	}

	writeMatchFunc(&buf, d, opts, ascii)

	if opts.Submatch != nil {
		fmt.Fprintf(&buf, "\n")
		GenerateSubmatch(&buf, *opts.Submatch)
	}

	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		// If formatting fails, write unformatted so user can debug
		_, werr := w.Write(buf.Bytes())
		if werr != nil {
			return werr
		}
		return fmt.Errorf("formatting generated code: %w", err)
	}

	_, err = w.Write(formatted)
	return err
}

func matchModeComment(mode MatchMode) string {
	switch mode {
	case MatchPrefix:
		return "reports whether a prefix of input matches"
	case MatchContains:
		return "reports whether any substring of input matches"
	default:
		return "reports whether input fully matches"
	}
}

func writeMatchFunc(buf *bytes.Buffer, d *dfa.DFA, opts Options, ascii bool) {
	fmt.Fprintf(buf, "// %s %s the regex %s.\n",
		opts.FuncName, matchModeComment(opts.Mode), quoteRegex(opts.Regex))
	fmt.Fprintf(buf, "func %s(input string) bool {\n", opts.FuncName)

	// Handle edge case: no states or no accepting states
	if len(d.States) == 0 {
		fmt.Fprintf(buf, "\treturn false\n")
		fmt.Fprintf(buf, "}\n")
		return
	}

	// Check if the start state is accepting (matches empty string)
	startAccepts := d.States[d.Start].Accept

	// If the DFA has only one state that is accepting with no transitions,
	// the regex matches only the empty string.
	if len(d.States) == 1 && startAccepts && len(d.States[0].Transitions) == 0 {
		if opts.Mode == MatchContains || opts.Mode == MatchPrefix {
			fmt.Fprintf(buf, "\treturn true\n")
		} else {
			fmt.Fprintf(buf, "\treturn len(input) == 0\n")
		}
		fmt.Fprintf(buf, "}\n")
		return
	}

	switch opts.Mode {
	case MatchPrefix:
		writeMatchPrefixBody(buf, d, ascii)
	case MatchContains:
		writeMatchContainsBody(buf, d, ascii)
	default:
		fmt.Fprintf(buf, "\tstate := %d\n", d.Start)
		if ascii {
			writeASCIILoop(buf, d)
		} else {
			writeUTF8Loop(buf, d)
		}
		writeAcceptCheck(buf, d)
	}

	fmt.Fprintf(buf, "}\n")
}

func writeMatchPrefixBody(buf *bytes.Buffer, d *dfa.DFA, ascii bool) {
	fmt.Fprintf(buf, "\tstate := %d\n", d.Start)
	if ascii {
		writeASCIILoopPrefix(buf, d)
	} else {
		writeUTF8LoopPrefix(buf, d)
	}
	writeAcceptCheck(buf, d)
}

func writeMatchContainsBody(buf *bytes.Buffer, d *dfa.DFA, ascii bool) {
	if ascii {
		writeASCIIContains(buf, d)
	} else {
		writeUTF8Contains(buf, d)
	}
}

func writeASCIILoop(buf *bytes.Buffer, d *dfa.DFA) {
	fmt.Fprintf(buf, "\tfor i := 0; i < len(input); i++ {\n")
	fmt.Fprintf(buf, "\t\tc := input[i]\n")
	fmt.Fprintf(buf, "\t\tswitch state {\n")

	for _, state := range d.States {
		if len(state.Transitions) == 0 && !state.Accept {
			continue // dead state, will be caught by default
		}
		fmt.Fprintf(buf, "\t\tcase %d:\n", state.ID)
		fmt.Fprintf(buf, "\t\t\tswitch {\n")
		for _, tr := range state.Transitions {
			writeByteCondition(buf, tr)
			fmt.Fprintf(buf, "\t\t\t\tstate = %d\n", tr.Next)
		}
		fmt.Fprintf(buf, "\t\t\tdefault:\n")
		fmt.Fprintf(buf, "\t\t\t\treturn false\n")
		fmt.Fprintf(buf, "\t\t\t}\n")
	}

	fmt.Fprintf(buf, "\t\tdefault:\n")
	fmt.Fprintf(buf, "\t\t\treturn false\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t}\n")
}

func writeUTF8Loop(buf *bytes.Buffer, d *dfa.DFA) {
	fmt.Fprintf(buf, "\tfor i := 0; i < len(input); {\n")
	fmt.Fprintf(buf, "\t\tr, size := utf8.DecodeRuneInString(input[i:])\n")
	fmt.Fprintf(buf, "\t\tif r == utf8.RuneError && size == 1 {\n")
	fmt.Fprintf(buf, "\t\t\treturn false\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\tswitch state {\n")

	for _, state := range d.States {
		if len(state.Transitions) == 0 && !state.Accept {
			continue
		}
		fmt.Fprintf(buf, "\t\tcase %d:\n", state.ID)
		fmt.Fprintf(buf, "\t\t\tswitch {\n")
		for _, tr := range state.Transitions {
			writeRuneCondition(buf, tr)
			fmt.Fprintf(buf, "\t\t\t\tstate = %d\n", tr.Next)
		}
		fmt.Fprintf(buf, "\t\t\tdefault:\n")
		fmt.Fprintf(buf, "\t\t\t\treturn false\n")
		fmt.Fprintf(buf, "\t\t\t}\n")
	}

	fmt.Fprintf(buf, "\t\tdefault:\n")
	fmt.Fprintf(buf, "\t\t\treturn false\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\ti += size\n")
	fmt.Fprintf(buf, "\t}\n")
}

// writeASCIILoopPrefix generates an ASCII loop that breaks (instead of returning false)
// when no transition matches, allowing prefix matching.
func writeASCIILoopPrefix(buf *bytes.Buffer, d *dfa.DFA) {
	fmt.Fprintf(buf, "\tfor i := 0; i < len(input); i++ {\n")
	fmt.Fprintf(buf, "\t\tc := input[i]\n")
	fmt.Fprintf(buf, "\t\tswitch state {\n")

	for _, state := range d.States {
		if len(state.Transitions) == 0 && !state.Accept {
			continue
		}
		fmt.Fprintf(buf, "\t\tcase %d:\n", state.ID)
		fmt.Fprintf(buf, "\t\t\tswitch {\n")
		for _, tr := range state.Transitions {
			writeByteCondition(buf, tr)
			fmt.Fprintf(buf, "\t\t\t\tstate = %d\n", tr.Next)
		}
		fmt.Fprintf(buf, "\t\t\tdefault:\n")
		fmt.Fprintf(buf, "\t\t\t\tgoto done\n")
		fmt.Fprintf(buf, "\t\t\t}\n")
	}

	fmt.Fprintf(buf, "\t\tdefault:\n")
	fmt.Fprintf(buf, "\t\t\tgoto done\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "done:\n")
}

// writeUTF8LoopPrefix generates a UTF-8 loop with prefix matching semantics.
func writeUTF8LoopPrefix(buf *bytes.Buffer, d *dfa.DFA) {
	fmt.Fprintf(buf, "\tfor i := 0; i < len(input); {\n")
	fmt.Fprintf(buf, "\t\tr, size := utf8.DecodeRuneInString(input[i:])\n")
	fmt.Fprintf(buf, "\t\tif r == utf8.RuneError && size == 1 {\n")
	fmt.Fprintf(buf, "\t\t\tgoto done\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\tswitch state {\n")

	for _, state := range d.States {
		if len(state.Transitions) == 0 && !state.Accept {
			continue
		}
		fmt.Fprintf(buf, "\t\tcase %d:\n", state.ID)
		fmt.Fprintf(buf, "\t\t\tswitch {\n")
		for _, tr := range state.Transitions {
			writeRuneCondition(buf, tr)
			fmt.Fprintf(buf, "\t\t\t\tstate = %d\n", tr.Next)
		}
		fmt.Fprintf(buf, "\t\t\tdefault:\n")
		fmt.Fprintf(buf, "\t\t\t\tgoto done\n")
		fmt.Fprintf(buf, "\t\t\t}\n")
	}

	fmt.Fprintf(buf, "\t\tdefault:\n")
	fmt.Fprintf(buf, "\t\t\tgoto done\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\ti += size\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "done:\n")
}

// writeASCIIContains generates an ASCII loop that tries matching from each position.
func writeASCIIContains(buf *bytes.Buffer, d *dfa.DFA) {
	fmt.Fprintf(buf, "\tfor start := 0; start <= len(input); start++ {\n")
	fmt.Fprintf(buf, "\t\tstate := %d\n", d.Start)

	// Check if start state accepts (empty pattern match at any position)
	if d.States[d.Start].Accept {
		fmt.Fprintf(buf, "\t\treturn true\n")
		fmt.Fprintf(buf, "\t}\n")
		return
	}

	fmt.Fprintf(buf, "\t\tmatched := false\n")
	fmt.Fprintf(buf, "\t\tfor i := start; i < len(input); i++ {\n")
	fmt.Fprintf(buf, "\t\t\tc := input[i]\n")
	fmt.Fprintf(buf, "\t\t\tdead := false\n")
	fmt.Fprintf(buf, "\t\t\tswitch state {\n")

	for _, state := range d.States {
		if len(state.Transitions) == 0 && !state.Accept {
			continue
		}
		fmt.Fprintf(buf, "\t\t\tcase %d:\n", state.ID)
		fmt.Fprintf(buf, "\t\t\t\tswitch {\n")
		for _, tr := range state.Transitions {
			writeByteConditionIndented(buf, tr, "\t\t\t\t")
			fmt.Fprintf(buf, "\t\t\t\t\tstate = %d\n", tr.Next)
		}
		fmt.Fprintf(buf, "\t\t\t\tdefault:\n")
		fmt.Fprintf(buf, "\t\t\t\t\tdead = true\n")
		fmt.Fprintf(buf, "\t\t\t\t}\n")
	}

	fmt.Fprintf(buf, "\t\t\tdefault:\n")
	fmt.Fprintf(buf, "\t\t\t\tdead = true\n")
	fmt.Fprintf(buf, "\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\tif dead {\n")
	fmt.Fprintf(buf, "\t\t\t\tbreak\n")
	fmt.Fprintf(buf, "\t\t\t}\n")

	// Check if we reached an accepting state after this character
	fmt.Fprintf(buf, "\t\t\tswitch state {\n")
	var acceptIDs []int
	for _, s := range d.States {
		if s.Accept {
			acceptIDs = append(acceptIDs, s.ID)
		}
	}
	if len(acceptIDs) > 0 {
		fmt.Fprintf(buf, "\t\t\tcase ")
		for i, id := range acceptIDs {
			if i > 0 {
				fmt.Fprintf(buf, ", ")
			}
			fmt.Fprintf(buf, "%d", id)
		}
		fmt.Fprintf(buf, ":\n")
		fmt.Fprintf(buf, "\t\t\t\tmatched = true\n")
	}
	fmt.Fprintf(buf, "\t\t\tdefault:\n")
	fmt.Fprintf(buf, "\t\t\t}\n")

	fmt.Fprintf(buf, "\t\t}\n") // end inner for
	fmt.Fprintf(buf, "\t\tif matched {\n")
	fmt.Fprintf(buf, "\t\t\treturn true\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t}\n") // end outer for
	fmt.Fprintf(buf, "\treturn false\n")
}

// writeUTF8Contains generates a UTF-8 loop that tries matching from each position.
func writeUTF8Contains(buf *bytes.Buffer, d *dfa.DFA) {
	fmt.Fprintf(buf, "\tfor start := 0; start <= len(input); {\n")
	fmt.Fprintf(buf, "\t\tstate := %d\n", d.Start)

	if d.States[d.Start].Accept {
		fmt.Fprintf(buf, "\t\treturn true\n")
		fmt.Fprintf(buf, "\t}\n")
		return
	}

	fmt.Fprintf(buf, "\t\tmatched := false\n")
	fmt.Fprintf(buf, "\t\tfor i := start; i < len(input); {\n")
	fmt.Fprintf(buf, "\t\t\tr, size := utf8.DecodeRuneInString(input[i:])\n")
	fmt.Fprintf(buf, "\t\t\tif r == utf8.RuneError && size == 1 {\n")
	fmt.Fprintf(buf, "\t\t\t\tbreak\n")
	fmt.Fprintf(buf, "\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\tdead := false\n")
	fmt.Fprintf(buf, "\t\t\tswitch state {\n")

	for _, state := range d.States {
		if len(state.Transitions) == 0 && !state.Accept {
			continue
		}
		fmt.Fprintf(buf, "\t\t\tcase %d:\n", state.ID)
		fmt.Fprintf(buf, "\t\t\t\tswitch {\n")
		for _, tr := range state.Transitions {
			writeRuneConditionIndented(buf, tr, "\t\t\t\t")
			fmt.Fprintf(buf, "\t\t\t\t\tstate = %d\n", tr.Next)
		}
		fmt.Fprintf(buf, "\t\t\t\tdefault:\n")
		fmt.Fprintf(buf, "\t\t\t\t\tdead = true\n")
		fmt.Fprintf(buf, "\t\t\t\t}\n")
	}

	fmt.Fprintf(buf, "\t\t\tdefault:\n")
	fmt.Fprintf(buf, "\t\t\t\tdead = true\n")
	fmt.Fprintf(buf, "\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\tif dead {\n")
	fmt.Fprintf(buf, "\t\t\t\tbreak\n")
	fmt.Fprintf(buf, "\t\t\t}\n")

	var acceptIDs []int
	for _, s := range d.States {
		if s.Accept {
			acceptIDs = append(acceptIDs, s.ID)
		}
	}
	fmt.Fprintf(buf, "\t\t\tswitch state {\n")
	if len(acceptIDs) > 0 {
		fmt.Fprintf(buf, "\t\t\tcase ")
		for i, id := range acceptIDs {
			if i > 0 {
				fmt.Fprintf(buf, ", ")
			}
			fmt.Fprintf(buf, "%d", id)
		}
		fmt.Fprintf(buf, ":\n")
		fmt.Fprintf(buf, "\t\t\t\tmatched = true\n")
	}
	fmt.Fprintf(buf, "\t\t\tdefault:\n")
	fmt.Fprintf(buf, "\t\t\t}\n")

	fmt.Fprintf(buf, "\t\t\ti += size\n")
	fmt.Fprintf(buf, "\t\t}\n") // end inner for
	fmt.Fprintf(buf, "\t\tif matched {\n")
	fmt.Fprintf(buf, "\t\t\treturn true\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\tif start < len(input) {\n")
	fmt.Fprintf(buf, "\t\t\t_, size := utf8.DecodeRuneInString(input[start:])\n")
	fmt.Fprintf(buf, "\t\t\tstart += size\n")
	fmt.Fprintf(buf, "\t\t} else {\n")
	fmt.Fprintf(buf, "\t\t\tstart++\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t}\n") // end outer for
	fmt.Fprintf(buf, "\treturn false\n")
}

func writeByteConditionIndented(buf *bytes.Buffer, tr dfa.Transition, indent string) {
	if tr.Lo == tr.Hi {
		fmt.Fprintf(buf, "%scase c == %s:\n", indent, quoteByte(byte(tr.Lo)))
	} else {
		fmt.Fprintf(buf, "%scase c >= %s && c <= %s:\n", indent, quoteByte(byte(tr.Lo)), quoteByte(byte(tr.Hi)))
	}
}

func writeRuneConditionIndented(buf *bytes.Buffer, tr dfa.Transition, indent string) {
	if tr.Lo == tr.Hi {
		fmt.Fprintf(buf, "%scase r == %s:\n", indent, quoteRune(tr.Lo))
	} else {
		fmt.Fprintf(buf, "%scase r >= %s && r <= %s:\n", indent, quoteRune(tr.Lo), quoteRune(tr.Hi))
	}
}

func writeAcceptCheck(buf *bytes.Buffer, d *dfa.DFA) {
	var acceptingStates []int
	for _, s := range d.States {
		if s.Accept {
			acceptingStates = append(acceptingStates, s.ID)
		}
	}

	if len(acceptingStates) == 0 {
		fmt.Fprintf(buf, "\treturn false\n")
		return
	}

	if len(acceptingStates) == 1 {
		fmt.Fprintf(buf, "\treturn state == %d\n", acceptingStates[0])
		return
	}

	fmt.Fprintf(buf, "\tswitch state {\n")
	fmt.Fprintf(buf, "\tcase ")
	for i, id := range acceptingStates {
		if i > 0 {
			fmt.Fprintf(buf, ", ")
		}
		fmt.Fprintf(buf, "%d", id)
	}
	fmt.Fprintf(buf, ":\n")
	fmt.Fprintf(buf, "\t\treturn true\n")
	fmt.Fprintf(buf, "\tdefault:\n")
	fmt.Fprintf(buf, "\t\treturn false\n")
	fmt.Fprintf(buf, "\t}\n")
}

func writeByteCondition(buf *bytes.Buffer, tr dfa.Transition) {
	if tr.Lo == tr.Hi {
		fmt.Fprintf(buf, "\t\t\tcase c == %s:\n", quoteByte(byte(tr.Lo)))
	} else {
		fmt.Fprintf(buf, "\t\t\tcase c >= %s && c <= %s:\n", quoteByte(byte(tr.Lo)), quoteByte(byte(tr.Hi)))
	}
}

func writeRuneCondition(buf *bytes.Buffer, tr dfa.Transition) {
	if tr.Lo == tr.Hi {
		fmt.Fprintf(buf, "\t\t\tcase r == %s:\n", quoteRune(tr.Lo))
	} else {
		fmt.Fprintf(buf, "\t\t\tcase r >= %s && r <= %s:\n", quoteRune(tr.Lo), quoteRune(tr.Hi))
	}
}

func quoteRune(r rune) string {
	return strconv.QuoteRune(r)
}

func quoteByte(b byte) string {
	return strconv.QuoteRune(rune(b))
}

func quoteRegex(s string) string {
	return "`" + s + "`"
}

// isASCIIOnly returns true if all DFA transitions only involve runes <= 127.
func isASCIIOnly(d *dfa.DFA) bool {
	for _, state := range d.States {
		for _, tr := range state.Transitions {
			if tr.Hi > unicode.MaxASCII {
				return false
			}
		}
	}
	return true
}
