package codegen

import (
	"strconv"
	"text/template"
)

var tmpl = template.Must(template.New("").Funcs(funcMap).Parse(allTemplates))

// goString emits a Go double-quoted string literal for s.
func goString(s string) string { return strconv.Quote(s) }

var funcMap = template.FuncMap{
	"quoteRegex":           quoteRegex,
	"goString":             goString,
	"isLive":               func(s templateState) bool { return len(s.Transitions) > 0 },
	"args":                 func(args ...any) []any { return args },
	"stateTransition":      stateTransition,
	"groupByteTransitions": groupByteTransitions,
	"groupRuneTransitions": groupRuneTransitions,
	"groupTransitions": func(kind string, s templateState) []groupedCase {
		if kind == "byte" {
			return groupByteTransitions(s)
		}
		return groupRuneTransitions(s)
	},
	"chainIndices": func(n int) []int {
		indices := make([]int, n)
		for i := range indices {
			indices[i] = i
		}
		return indices
	},
}

const allTemplates = headerTemplate +
	matchFuncTemplate +
	edgeCaseEmptyTemplate +
	edgeCaseEmptyMatchTemplate +
	fullBodyTemplate +
	prefixBodyTemplate +
	containsBodyTemplate +
	asciiLoopTemplate +
	utf8LoopTemplate +
	asciiLoopPrefixTemplate +
	utf8LoopPrefixTemplate +
	asciiContainsTemplate +
	utf8ContainsTemplate +
	statesTemplate +
	statesContainsTemplate +
	acceptCheckTemplate +
	acceptIDsTemplate +
	submatchFuncTemplate +
	submatchIndexFuncTemplate +
	submatchStringFuncTemplate +
	submatchNamesFuncTemplate +
	submatchStructFuncTemplate +
	nfaTableTemplate +
	nfaSimTemplate

// ---------- header ----------

const headerTemplate = `
{{- define "header" -}}
// Code generated by go-regex-compiler. DO NOT EDIT.
// Source regex: {{ quoteRegex .Regex }}

package {{ .PackageName }}

{{ if .HasRanges }}
import "github.com/wow-look-at-my/go-regex-compiler/match"
{{ end }}
{{ if not .ASCII }}
import "unicode/utf8"
{{ end }}
{{ end -}}
`

// ---------- match function ----------

const matchFuncTemplate = `
{{- define "matchFunc" -}}
// {{ .FuncName }} {{ .ModeComment }} the regex {{ quoteRegex .Regex }}.
func {{ .FuncName }}(input string) bool {
{{- if eq (len .States) 0 }}
	return false
{{- else if .EdgeCase }}
{{ template "edgeCaseEmpty" . }}
{{- else if eq .Mode "full" -}}
{{ template "fullBody" . }}
{{- else if eq .Mode "prefix" -}}
{{ template "prefixBody" . }}
{{- else if eq .Mode "contains" -}}
{{ template "containsBody" . }}
{{- end }}
}
{{ end -}}
`

const edgeCaseEmptyTemplate = `
{{- define "edgeCaseEmpty" -}}
{{- if .EdgeCaseAlwaysTrue }}
	return true
{{- else }}
	return len(input) == 0
{{- end }}
{{- end -}}
`

const edgeCaseEmptyMatchTemplate = "" // placeholder for future use

// ---------- full match body ----------

const fullBodyTemplate = `
{{- define "fullBody" }}
	state := {{ .Start }}
{{- range chainIndices .NumChains }}
	chainCount{{ . }} := 0
{{- end }}
{{- if .ASCII -}}
{{ template "asciiLoop" . }}
{{- else -}}
{{ template "utf8Loop" . }}
{{- end }}
{{ template "acceptCheck" . }}
{{- end -}}
`

// ---------- prefix body ----------

const prefixBodyTemplate = `
{{- define "prefixBody" }}
	state := {{ .Start }}
{{- range chainIndices .NumChains }}
	chainCount{{ . }} := 0
{{- end }}
{{- if .ASCII -}}
{{ template "asciiLoopPrefix" . }}
{{- else -}}
{{ template "utf8LoopPrefix" . }}
{{- end }}
{{ template "acceptCheck" . }}
{{- end -}}
`

// ---------- contains body ----------

const containsBodyTemplate = `
{{- define "containsBody" -}}
{{- if .ASCII -}}
{{ template "asciiContains" . }}
{{- else -}}
{{ template "utf8Contains" . }}
{{- end }}
{{- end -}}
`

// ---------- loops ----------

const asciiLoopTemplate = `
{{- define "asciiLoop" }}
	for i := 0; i < len(input); i++ {
		c := input[i]
		switch state {
{{ template "statesASCII" . }}
		default:
			return false
		}
	}
{{- end -}}
`

const utf8LoopTemplate = `
{{- define "utf8Loop" }}
	for i := 0; i < len(input); {
		r, size := utf8.DecodeRuneInString(input[i:])
		if r == utf8.RuneError && size == 1 {
			return false
		}
		switch state {
{{ template "statesRune" . }}
		default:
			return false
		}
		i += size
	}
{{- end -}}
`

const asciiLoopPrefixTemplate = `
{{- define "asciiLoopPrefix" }}
	for i := 0; i < len(input); i++ {
		c := input[i]
		switch state {
{{ template "statesASCIIPrefix" . }}
		default:
			goto done
		}
	}
done:
{{- end -}}
`

const utf8LoopPrefixTemplate = `
{{- define "utf8LoopPrefix" }}
	for i := 0; i < len(input); {
		r, size := utf8.DecodeRuneInString(input[i:])
		if r == utf8.RuneError && size == 1 {
			goto done
		}
		switch state {
{{ template "statesRunePrefix" . }}
		default:
			goto done
		}
		i += size
	}
done:
{{- end -}}
`

// ---------- contains loops ----------

const asciiContainsTemplate = `
{{- define "asciiContains" }}
{{- if .StartAccepts }}
	return true
{{- else }}
	for start := 0; start <= len(input); start++ {
		state := {{ .Start }}
{{- range chainIndices .NumChains }}
		chainCount{{ . }} := 0
{{- end }}
		matched := false
		for i := start; i < len(input); i++ {
			c := input[i]
			dead := false
			switch state {
{{ template "statesASCIIContains" . }}
			default:
				dead = true
			}
			if dead {
				break
			}
			switch state {
{{ template "acceptIDs" . }}
				matched = true
			default:
			}
		}
		if matched {
			return true
		}
	}
	return false
{{- end }}
{{- end -}}
`

const utf8ContainsTemplate = `
{{- define "utf8Contains" }}
{{- if .StartAccepts }}
	return true
{{- else }}
	for start := 0; start <= len(input); {
		state := {{ .Start }}
{{- range chainIndices .NumChains }}
		chainCount{{ . }} := 0
{{- end }}
		matched := false
		for i := start; i < len(input); {
			r, size := utf8.DecodeRuneInString(input[i:])
			if r == utf8.RuneError && size == 1 {
				break
			}
			dead := false
			switch state {
{{ template "statesRuneContains" . }}
			default:
				dead = true
			}
			if dead {
				break
			}
			switch state {
{{ template "acceptIDs" . }}
				matched = true
			default:
			}
			i += size
		}
		if matched {
			return true
		}
		if start < len(input) {
			_, size := utf8.DecodeRuneInString(input[start:])
			start += size
		} else {
			start++
		}
	}
	return false
{{- end }}
{{- end -}}
`

// ---------- state switch cases ----------

// statesInner handles full/prefix; statesContainsInner handles contains.
// Byte vs rune condition and the no-match action are passed as parameters.

const statesTemplate = `
{{- define "statesASCII" }}{{ template "statesInner" (args . "byte" "return false") }}{{ end }}
{{- define "statesASCIIPrefix" }}{{ template "statesInner" (args . "byte" "goto done") }}{{ end }}
{{- define "statesRune" }}{{ template "statesInner" (args . "rune" "return false") }}{{ end }}
{{- define "statesRunePrefix" }}{{ template "statesInner" (args . "rune" "goto done") }}{{ end }}
{{- define "statesInner" -}}
{{- $ctx := index . 0 -}}
{{- $condKind := index . 1 -}}
{{- $noMatch := index . 2 -}}
{{- range $ctx.States }}{{ if isLive . }}
		case {{ .ID }}:
			switch {
{{- range groupTransitions $condKind . }}
			case {{ .Cond }}: {{ .Body }}
{{- end }}
			default: {{ $noMatch }}
			}
{{- end }}{{ end }}
{{- end -}}
`

const statesContainsTemplate = `
{{- define "statesASCIIContains" }}{{ template "statesContainsInner" (args . "byte") }}{{ end }}
{{- define "statesRuneContains" }}{{ template "statesContainsInner" (args . "rune") }}{{ end }}
{{- define "statesContainsInner" -}}
{{- $ctx := index . 0 -}}
{{- $condKind := index . 1 -}}
{{- range $ctx.States }}{{ if isLive . }}
			case {{ .ID }}:
				switch {
{{- range groupTransitions $condKind . }}
				case {{ .Cond }}: {{ .Body }}
{{- end }}
				default: dead = true
				}
{{- end }}{{ end }}
{{- end -}}
`

// ---------- accept check ----------

const acceptCheckTemplate = `
{{- define "acceptCheck" -}}
{{- if eq (len .AcceptIDs) 0 }}
	return false
{{- else if eq (len .AcceptIDs) 1 }}
	return state == {{ index .AcceptIDs 0 }}
{{- else }}
	switch state {
	case {{ range $i, $id := .AcceptIDs }}{{ if $i }}, {{ end }}{{ $id }}{{ end }}:
		return true
	default:
		return false
	}
{{- end }}
{{- end -}}
`

const acceptIDsTemplate = `
{{- define "acceptIDs" -}}
{{- if gt (len .AcceptIDs) 0 }}
			case {{ range $i, $id := .AcceptIDs }}{{ if $i }}, {{ end }}{{ $id }}{{ end }}:
{{- end }}
{{- end -}}
`

// ---------- submatch ----------
//
// The submatch family shares a single Thompson NFA core, emitted once in the
// <FuncName>Index function. The other accessors are thin wrappers over it so
// the (potentially large) instruction table is never duplicated.

const submatchFuncTemplate = `
{{- define "submatchFunc" -}}
{{ template "submatchIndexFunc" . }}
{{ template "submatchStringFunc" . }}
{{ template "submatchNamesFunc" . }}
{{- if .EmitStruct }}
{{ template "submatchStructFunc" . }}
{{- end }}
{{ end -}}
`

// ---------- index core ----------

const nfaTableTemplate = `
{{- define "nfaTable" -}}
	// NFA instruction types
	const (
		opRune      = 0
		opRune1     = 1
		opRuneAny   = 2
		opRuneAnyNL = 3
		opAlt       = 4
		opCapture   = 5
		opMatch     = 6
		opNop       = 7
		opFail      = 8
		opEmpty     = 9
	)

	// Empty-width assertion bits (from regexp/syntax.EmptyOp), inlined so the
	// generated code does not import regexp/syntax.
	const (
		emptyBeginLine      = 1
		emptyEndLine        = 2
		emptyBeginText      = 4
		emptyEndText        = 8
		emptyWordBoundary   = 16
		emptyNoWordBoundary = 32
	)

	type nfaInst struct {
		op   int
		out  int
		arg  int
		runes []rune
	}

	prog := []nfaInst{
{{- range .Instructions }}
		/* {{ .Index }} */ {op: {{ .OpName }}, out: {{ .Out }}, arg: {{ .Arg }}{{ if .Runes }}, runes: {{ .Runes }}{{ end }}},
{{- end }}
	}
	startPC := {{ .StartPC }}
{{ end -}}
`

const submatchIndexFuncTemplate = `
{{- define "submatchIndexFunc" -}}
// {{ .IndexFuncName }} returns the submatch index slice for the regex {{ quoteRegex .Regex }},
// or nil if the input does not match. The slice has length 2*(N+1) where N is
// the number of capture groups: pair (2*g, 2*g+1) holds the absolute byte
// offsets [start, end) of group g, with index 0 being the whole match. A
// non-participating group has the pair (-1, -1). This is parity with
// regexp.Regexp.FindStringSubmatchIndex.
func {{ .IndexFuncName }}(input string) []int {
	if !{{ .MatchFunc }}(input) {
		return nil
	}
{{ template "nfaTable" . }}
{{ template "nfaSim" . }}
}
{{ end -}}
`

const nfaSimTemplate = `
{{- define "nfaSim" -}}
	// isWordChar reports whether r is a word character ([0-9A-Za-z_]).
	isWordChar := func(r rune) bool {
		return r == '_' ||
			(r >= '0' && r <= '9') ||
			(r >= 'a' && r <= 'z') ||
			(r >= 'A' && r <= 'Z')
	}

	// emptyOpsAt computes the satisfied empty-width assertion bits at the
	// boundary between the rune before (bp) and the rune after (ap) the current
	// position. bp/ap are -1 at the text edges.
	emptyOpsAt := func(bp, ap rune) int {
		var op int
		if bp < 0 {
			op |= emptyBeginText | emptyBeginLine
		}
		if bp == '\n' {
			op |= emptyBeginLine
		}
		if ap < 0 {
			op |= emptyEndText | emptyEndLine
		}
		if ap == '\n' {
			op |= emptyEndLine
		}
		beforeWord := bp >= 0 && isWordChar(bp)
		afterWord := ap >= 0 && isWordChar(ap)
		if beforeWord != afterWord {
			op |= emptyWordBoundary
		} else {
			op |= emptyNoWordBoundary
		}
		return op
	}

	// Thompson NFA simulation with capture tracking. Thread priority is
	// preserved (leftmost-first, matching Go's default regexp engine): the
	// stack-based closure explores the high-priority branch (out) before the
	// low-priority branch (arg) of each alternation.
	type thread struct {
		pc   int
		caps [{{ .NumSlots }}]int
	}

	addThread := func(list []thread, pc int, caps [{{ .NumSlots }}]int, pos int, before, after rune) []thread {
		visited := make(map[int]bool)
		type frame struct {
			pc   int
			caps [{{ .NumSlots }}]int
		}
		var stack []frame
		stack = append(stack, frame{pc: pc, caps: caps})
		// emptyOps for this position, computed lazily on the first opEmpty.
		ops := -1
		for len(stack) > 0 {
			f := stack[len(stack)-1]
			stack = stack[:len(stack)-1]
			if f.pc < 0 || f.pc >= len(prog) || visited[f.pc] {
				continue
			}
			visited[f.pc] = true
			inst := &prog[f.pc]
			switch inst.op {
			case opAlt:
				// Push low priority first so high priority (out) is processed first.
				stack = append(stack, frame{pc: inst.arg, caps: f.caps})
				stack = append(stack, frame{pc: int(inst.out), caps: f.caps})
			case opNop:
				stack = append(stack, frame{pc: int(inst.out), caps: f.caps})
			case opEmpty:
				if ops < 0 {
					ops = emptyOpsAt(before, after)
				}
				// The assertion holds iff every required bit is satisfied.
				if inst.arg&^ops == 0 {
					stack = append(stack, frame{pc: int(inst.out), caps: f.caps})
				}
			case opCapture:
				newCaps := f.caps
				if inst.arg < {{ .NumSlots }} {
					newCaps[inst.arg] = pos
				}
				stack = append(stack, frame{pc: int(inst.out), caps: newCaps})
			default:
				list = append(list, thread{pc: f.pc, caps: f.caps})
			}
		}
		return list
	}

	runeMatch := func(inst *nfaInst, r rune) bool {
		switch inst.op {
		case opRuneAny:
			return true
		case opRuneAnyNL:
			return r != '\n'
		case opRune1:
			if len(inst.runes) > 0 && inst.runes[0] == r {
				return true
			}
			return false
		case opRune:
			for i := 0; i < len(inst.runes)-1; i += 2 {
				if r >= inst.runes[i] && r <= inst.runes[i+1] {
					return true
				}
			}
			if len(inst.runes)%2 == 1 {
				if r == inst.runes[len(inst.runes)-1] {
					return true
				}
			}
			return false
		}
		return false
	}

	// Decode the input into runes once (range over a string decodes UTF-8
	// natively, so no unicode/utf8 import is needed). runes[k] is the k-th rune
	// and offs[k] its starting byte offset; offs[len(runes)] == len(input).
	// len(input) is a safe upper bound on the rune count, so preallocate both.
	runes := make([]rune, 0, len(input))
	offs := make([]int, 0, len(input)+1)
	for i, r := range input {
		runes = append(runes, r)
		offs = append(offs, i)
	}
	offs = append(offs, len(input))

	var initCaps [{{ .NumSlots }}]int
	for i := range initCaps {
		initCaps[i] = -1
	}
	initCaps[0] = 0 // group 0 start = beginning of input

	// Seed at position 0. before = -1 (text begin); after = first rune (or -1).
	var firstRune rune = -1
	if len(runes) > 0 {
		firstRune = runes[0]
	}
	current := addThread(nil, startPC, initCaps, 0, -1, firstRune)

	for k := 0; k < len(runes); k++ {
		r := runes[k]
		nextPos := offs[k+1]
		// before for the NEXT boundary is r; after is the rune after k (or -1).
		var afterRune rune = -1
		if k+1 < len(runes) {
			afterRune = runes[k+1]
		}
		var next []thread
		for _, t := range current {
			inst := &prog[t.pc]
			if runeMatch(inst, r) {
				next = addThread(next, int(inst.out), t.caps, nextPos, r, afterRune)
			}
		}
		current = next
	}

	for _, t := range current {
		if t.pc < len(prog) && prog[t.pc].op == opMatch {
			t.caps[1] = len(input) // group 0 end
			result := make([]int, {{ .NumSlots }})
			copy(result, t.caps[:])
			return result
		}
	}
	return nil
{{- end -}}
`

// ---------- string wrapper ----------

const submatchStringFuncTemplate = `
{{- define "submatchStringFunc" -}}
// {{ .FuncName }} returns captured groups for the regex {{ quoteRegex .Regex }}.
// Returns nil if the input does not match. Index 0 is the entire match,
// indices 1..N are capture groups. A group that did not participate in the
// match yields "" (parity with regexp.Regexp.FindStringSubmatch); use
// {{ .IndexFuncName }} to distinguish an absent group (offset pair -1) from an
// empty one.
func {{ .FuncName }}(input string) []string {
	idx := {{ .IndexFuncName }}(input)
	if idx == nil {
		return nil
	}
	result := make([]string, {{ .NumGroups }})
	for g := 0; g < {{ .NumGroups }}; g++ {
		s, e := idx[g*2], idx[g*2+1]
		if s >= 0 && e >= 0 && s <= len(input) && e <= len(input) {
			result[g] = input[s:e]
		}
	}
	return result
}
{{ end -}}
`

// ---------- names accessor ----------

const submatchNamesFuncTemplate = `
{{- define "submatchNamesFunc" -}}
// {{ .NamesFuncName }} returns the names of the capture groups for the regex
// {{ quoteRegex .Regex }}. The slice has one entry per group index: index 0 (the
// whole match) is always "", and an unnamed group is "". This is parity with
// regexp.Regexp.SubexpNames.
func {{ .NamesFuncName }}() []string {
	return []string{{"{"}}{{ range $i, $n := .GroupNames }}{{ if $i }}, {{ end }}{{ goString $n }}{{ end }}}
}
{{ end -}}
`

// ---------- typed struct ----------

const submatchStructFuncTemplate = `
{{- define "submatchStructFunc" -}}
// {{ .StructType }} holds the named capture groups extracted from a match.
// Matched reports whether the input matched at all (distinguishing a non-match
// from a match where every named group is empty).
//
// NOTE: two regex group names that differ only by the case of their first
// rune (e.g. "ip" and "Ip") collide into a single exported field here; the
// last such group wins. See the README for details.
type {{ .StructType }} struct {
{{- range .StructFields }}
	{{ .Name }} string
{{- end }}
	Matched bool
}

// {{ .StructFunc }} extracts the named capture groups of the regex
// {{ quoteRegex .Regex }} from input. On no match it returns the zero value
// ({{ .StructType }}{Matched: false} with all fields ""). Otherwise each field
// is filled from its group (an unmatched optional group yields "").
func {{ .StructFunc }}(input string) {{ .StructType }} {
	groups := {{ .FuncName }}(input)
	if groups == nil {
		return {{ .StructType }}{}
	}
	return {{ .StructType }}{
{{- range .StructFields }}
		{{ .Name }}: groups[{{ .Group }}],
{{- end }}
		Matched: true,
	}
}
{{ end -}}
`
