package codegen

import (
	"strconv"
	"text/template"
)

var tmpl = template.Must(template.New("").Funcs(funcMap).Parse(allTemplates))

// goString emits a Go double-quoted string literal for s.
func goString(s string) string { return strconv.Quote(s) }

var funcMap = template.FuncMap{
	"quoteRegex":           quoteRegex,
	"goString":             goString,
	"isLive":               func(s templateState) bool { return len(s.Transitions) > 0 },
	"args":                 func(args ...any) []any { return args },
	"stateTransition":      stateTransition,
	"groupByteTransitions": groupByteTransitions,
	"groupRuneTransitions": groupRuneTransitions,
	"groupTransitions": func(kind string, s templateState) []groupedCase {
		if kind == "byte" {
			return groupByteTransitions(s)
		}
		return groupRuneTransitions(s)
	},
	"chainIndices": func(n int) []int {
		indices := make([]int, n)
		for i := range indices {
			indices[i] = i
		}
		return indices
	},
}

const allTemplates = headerTemplate +
	matchFuncTemplate +
	edgeCaseEmptyTemplate +
	edgeCaseEmptyMatchTemplate +
	fullBodyTemplate +
	prefixBodyTemplate +
	containsBodyTemplate +
	asciiLoopTemplate +
	utf8LoopTemplate +
	asciiLoopPrefixTemplate +
	utf8LoopPrefixTemplate +
	asciiContainsTemplate +
	utf8ContainsTemplate +
	statesTemplate +
	statesContainsTemplate +
	acceptCheckTemplate +
	acceptIDsTemplate +
	submatchFuncTemplate +
	submatchIndexFuncTemplate +
	submatchStringFuncTemplate +
	submatchNamesFuncTemplate +
	submatchStructFuncTemplate +
	nfaPackageDeclsTemplate +
	nfaSimTemplate +
	onepassIndexFuncTemplate

// ---------- header ----------

const headerTemplate = `
{{- define "header" -}}
// Code generated by go-regex-compiler. DO NOT EDIT.
// Source regex: {{ quoteRegex .Regex }}

package {{ .PackageName }}

{{ if .NeedMatch }}
import "github.com/wow-look-at-my/go-regex-compiler/match"
{{ end }}
{{ if .NeedUTF8 }}
import "unicode/utf8"
{{ end }}
{{ if .NeedSync }}
import "sync"
{{ end }}
{{ end -}}
`

// ---------- match function ----------

const matchFuncTemplate = `
{{- define "matchFunc" -}}
// {{ .FuncName }} {{ .ModeComment }} the regex {{ quoteRegex .Regex }}.
func {{ .FuncName }}(input string) bool {
{{- if eq (len .States) 0 }}
	return false
{{- else if .EdgeCase }}
{{ template "edgeCaseEmpty" . }}
{{- else if eq .Mode "full" -}}
{{ template "fullBody" . }}
{{- else if eq .Mode "prefix" -}}
{{ template "prefixBody" . }}
{{- else if eq .Mode "contains" -}}
{{ template "containsBody" . }}
{{- end }}
}
{{ end -}}
`

const edgeCaseEmptyTemplate = `
{{- define "edgeCaseEmpty" -}}
{{- if .EdgeCaseAlwaysTrue }}
	return true
{{- else }}
	return len(input) == 0
{{- end }}
{{- end -}}
`

const edgeCaseEmptyMatchTemplate = "" // placeholder for future use

// ---------- full match body ----------

const fullBodyTemplate = `
{{- define "fullBody" }}
	state := {{ .Start }}
{{- range chainIndices .NumChains }}
	chainCount{{ . }} := 0
{{- end }}
{{- if .ASCII -}}
{{ template "asciiLoop" . }}
{{- else -}}
{{ template "utf8Loop" . }}
{{- end }}
{{ template "acceptCheck" . }}
{{- end -}}
`

// ---------- prefix body ----------

const prefixBodyTemplate = `
{{- define "prefixBody" }}
	state := {{ .Start }}
{{- range chainIndices .NumChains }}
	chainCount{{ . }} := 0
{{- end }}
{{- if .ASCII -}}
{{ template "asciiLoopPrefix" . }}
{{- else -}}
{{ template "utf8LoopPrefix" . }}
{{- end }}
{{ template "acceptCheck" . }}
{{- end -}}
`

// ---------- contains body ----------

const containsBodyTemplate = `
{{- define "containsBody" -}}
{{- if .ASCII -}}
{{ template "asciiContains" . }}
{{- else -}}
{{ template "utf8Contains" . }}
{{- end }}
{{- end -}}
`

// ---------- loops ----------

const asciiLoopTemplate = `
{{- define "asciiLoop" }}
	for i := 0; i < len(input); i++ {
		c := input[i]
		switch state {
{{ template "statesASCII" . }}
		default:
			return false
		}
	}
{{- end -}}
`

const utf8LoopTemplate = `
{{- define "utf8Loop" }}
	for i := 0; i < len(input); {
		r, size := utf8.DecodeRuneInString(input[i:])
		if r == utf8.RuneError && size == 1 {
			return false
		}
		switch state {
{{ template "statesRune" . }}
		default:
			return false
		}
		i += size
	}
{{- end -}}
`

const asciiLoopPrefixTemplate = `
{{- define "asciiLoopPrefix" }}
	for i := 0; i < len(input); i++ {
		c := input[i]
		switch state {
{{ template "statesASCIIPrefix" . }}
		default:
			goto done
		}
	}
done:
{{- end -}}
`

const utf8LoopPrefixTemplate = `
{{- define "utf8LoopPrefix" }}
	for i := 0; i < len(input); {
		r, size := utf8.DecodeRuneInString(input[i:])
		if r == utf8.RuneError && size == 1 {
			goto done
		}
		switch state {
{{ template "statesRunePrefix" . }}
		default:
			goto done
		}
		i += size
	}
done:
{{- end -}}
`

// ---------- contains loops ----------

const asciiContainsTemplate = `
{{- define "asciiContains" }}
{{- if .StartAccepts }}
	return true
{{- else }}
	for start := 0; start <= len(input); start++ {
		state := {{ .Start }}
{{- range chainIndices .NumChains }}
		chainCount{{ . }} := 0
{{- end }}
		matched := false
		for i := start; i < len(input); i++ {
			c := input[i]
			dead := false
			switch state {
{{ template "statesASCIIContains" . }}
			default:
				dead = true
			}
			if dead {
				break
			}
			switch state {
{{ template "acceptIDs" . }}
				matched = true
			default:
			}
		}
		if matched {
			return true
		}
	}
	return false
{{- end }}
{{- end -}}
`

const utf8ContainsTemplate = `
{{- define "utf8Contains" }}
{{- if .StartAccepts }}
	return true
{{- else }}
	for start := 0; start <= len(input); {
		state := {{ .Start }}
{{- range chainIndices .NumChains }}
		chainCount{{ . }} := 0
{{- end }}
		matched := false
		for i := start; i < len(input); {
			r, size := utf8.DecodeRuneInString(input[i:])
			if r == utf8.RuneError && size == 1 {
				break
			}
			dead := false
			switch state {
{{ template "statesRuneContains" . }}
			default:
				dead = true
			}
			if dead {
				break
			}
			switch state {
{{ template "acceptIDs" . }}
				matched = true
			default:
			}
			i += size
		}
		if matched {
			return true
		}
		if start < len(input) {
			_, size := utf8.DecodeRuneInString(input[start:])
			start += size
		} else {
			start++
		}
	}
	return false
{{- end }}
{{- end -}}
`

// ---------- state switch cases ----------

// statesInner handles full/prefix; statesContainsInner handles contains.
// Byte vs rune condition and the no-match action are passed as parameters.

const statesTemplate = `
{{- define "statesASCII" }}{{ template "statesInner" (args . "byte" "return false") }}{{ end }}
{{- define "statesASCIIPrefix" }}{{ template "statesInner" (args . "byte" "goto done") }}{{ end }}
{{- define "statesRune" }}{{ template "statesInner" (args . "rune" "return false") }}{{ end }}
{{- define "statesRunePrefix" }}{{ template "statesInner" (args . "rune" "goto done") }}{{ end }}
{{- define "statesInner" -}}
{{- $ctx := index . 0 -}}
{{- $condKind := index . 1 -}}
{{- $noMatch := index . 2 -}}
{{- range $ctx.States }}{{ if isLive . }}
		case {{ .ID }}:
			switch {
{{- range groupTransitions $condKind . }}
			case {{ .Cond }}: {{ .Body }}
{{- end }}
			default: {{ $noMatch }}
			}
{{- end }}{{ end }}
{{- end -}}
`

const statesContainsTemplate = `
{{- define "statesASCIIContains" }}{{ template "statesContainsInner" (args . "byte") }}{{ end }}
{{- define "statesRuneContains" }}{{ template "statesContainsInner" (args . "rune") }}{{ end }}
{{- define "statesContainsInner" -}}
{{- $ctx := index . 0 -}}
{{- $condKind := index . 1 -}}
{{- range $ctx.States }}{{ if isLive . }}
			case {{ .ID }}:
				switch {
{{- range groupTransitions $condKind . }}
				case {{ .Cond }}: {{ .Body }}
{{- end }}
				default: dead = true
				}
{{- end }}{{ end }}
{{- end -}}
`

// ---------- accept check ----------

const acceptCheckTemplate = `
{{- define "acceptCheck" -}}
{{- if eq (len .AcceptIDs) 0 }}
	return false
{{- else if eq (len .AcceptIDs) 1 }}
	return state == {{ index .AcceptIDs 0 }}
{{- else }}
	switch state {
	case {{ range $i, $id := .AcceptIDs }}{{ if $i }}, {{ end }}{{ $id }}{{ end }}:
		return true
	default:
		return false
	}
{{- end }}
{{- end -}}
`

const acceptIDsTemplate = `
{{- define "acceptIDs" -}}
{{- if gt (len .AcceptIDs) 0 }}
			case {{ range $i, $id := .AcceptIDs }}{{ if $i }}, {{ end }}{{ $id }}{{ end }}:
{{- end }}
{{- end -}}
`
