package codegen

import (
	"strconv"
	"text/template"
)

var tmpl = template.Must(template.New("").Funcs(funcMap).Parse(allTemplates))

// goString emits a Go double-quoted string literal for s.
func goString(s string) string { return strconv.Quote(s) }

var funcMap = template.FuncMap{
	"quoteRegex":           quoteRegex,
	"goString":             goString,
	"isLive":               func(s templateState) bool { return len(s.Transitions) > 0 },
	"args":                 func(args ...any) []any { return args },
	"stateTransition":      stateTransition,
	"quoteByte":            quoteByte,
	"groupByteTransitions": groupByteTransitions,
	"groupRuneTransitions": groupRuneTransitions,
	"groupTransitions": func(ctx templateContext, kind string, s templateState) []groupedCase {
		if kind == "byte" {
			return groupByteTransitions(ctx, s)
		}
		return groupRuneTransitions(ctx, s)
	},
	"chainIndices": func(n int) []int {
		indices := make([]int, n)
		for i := range indices {
			indices[i] = i
		}
		return indices
	},
}

const allTemplates = headerTemplate +
	matchFuncTemplate +
	edgeCaseEmptyTemplate +
	edgeCaseEmptyMatchTemplate +
	fullBodyTemplate +
	prefixBodyTemplate +
	containsBodyTemplate +
	asciiLoopTemplate +
	utf8LoopTemplate +
	asciiSearchLoopTemplate +
	utf8SearchLoopTemplate +
	statesTemplate +
	acceptCheckTemplate +
	submatchFuncTemplate +
	submatchStringFuncTemplate +
	submatchNamesFuncTemplate +
	submatchStructFuncTemplate +
	onepassIndexFuncTemplate +
	tdfaIndexFuncTemplate

// ---------- header ----------

const headerTemplate = `
{{- define "header" -}}
// Code generated by go-regex-compiler. DO NOT EDIT.
// Source regex: {{ quoteRegex .Regex }}

package {{ .PackageName }}

{{ if .NeedMatch }}
import "github.com/wow-look-at-my/go-regex-compiler/match"
{{ end }}
{{ if or .SkipToByte .LiteralContains }}
import "strings"
{{ end }}
{{ if .NeedUTF8 }}
import "unicode/utf8"
{{ end }}
{{ end -}}
`

// ---------- match function ----------

const matchFuncTemplate = `
{{- define "matchFunc" -}}
// {{ .FuncName }} {{ .ModeComment }} the regex {{ quoteRegex .Regex }}.
func {{ .FuncName }}(input string) bool {
{{- if eq (len .States) 0 }}
	return false
{{- else if .EdgeCase }}
{{ template "edgeCaseEmpty" . }}
{{- else if eq .Mode "full" -}}
{{ template "fullBody" . }}
{{- else if eq .Mode "prefix" -}}
{{ template "prefixBody" . }}
{{- else if eq .Mode "contains" -}}
{{ template "containsBody" . }}
{{- end }}
}
{{ end -}}
`

const edgeCaseEmptyTemplate = `
{{- define "edgeCaseEmpty" -}}
{{- if .EdgeCaseAlwaysTrue }}
	return true
{{- else }}
	return len(input) == 0
{{- end }}
{{- end -}}
`

const edgeCaseEmptyMatchTemplate = "" // placeholder for future use

// ---------- full match body ----------

const fullBodyTemplate = `
{{- define "fullBody" }}
	state := {{ .Start }}
{{- range chainIndices .NumChains }}
	chainCount{{ . }} := 0
{{- end }}
{{- if .ASCII -}}
{{ template "asciiLoop" . }}
{{- else -}}
{{ template "utf8Loop" . }}
{{- end }}
{{ template "acceptCheck" . }}
{{- end -}}
`

// ---------- prefix body ----------
//
// Prefix mode returns true the moment ANY accepting state is entered: a match
// found mid-input proves some prefix matches, even if the DFA later dies. (The
// old shape — run until dead and test the final state — missed matches that
// passed THROUGH an accepting state, e.g. `a(bc)?` against "abx".) Accepting
// states are unreachable under this scheme, so the loop only ever holds
// non-accepting states, and running out of input or transitions means no
// prefix matched.

const prefixBodyTemplate = `
{{- define "prefixBody" }}
{{- if .StartAccepts }}
	return true
{{- else }}
	state := {{ .Start }}
{{- range chainIndices .NumChains }}
	chainCount{{ . }} := 0
{{- end }}
{{- if .ASCII -}}
{{ template "asciiLoop" . }}
{{- else -}}
{{ template "utf8Loop" . }}
{{- end }}
	return false
{{- end }}
{{- end -}}
`

// ---------- contains body ----------
//
// Contains mode runs a SEARCH DFA (dfa.BuildSearch): the start closure is
// folded into every state, so one left-to-right pass tracks every possible
// match start simultaneously. Entering an accepting state proves a substring
// match (EarlyAccept renders those transitions as "return true"), and a rune
// with no transition simply restarts at the start state -- the builder omits
// those edges and the switch default handles them. This replaces the old
// O(n^2) restart-the-DFA-at-every-position loop with a single O(n) scan.

const containsBodyTemplate = `
{{- define "containsBody" }}
{{- if .StartAccepts }}
	return true
{{- else if .LiteralContains }}
	return strings.Contains(input, {{ goString .Literal }})
{{- else }}
	state := {{ .Start }}
{{- range chainIndices .NumChains }}
	chainCount{{ . }} := 0
{{- end }}
{{- if .ASCII -}}
{{ template "asciiSearchLoop" . }}
{{- else -}}
{{ template "utf8SearchLoop" . }}
{{- end }}
	return false
{{- end }}
{{- end -}}
`

// ---------- loops ----------

const asciiLoopTemplate = `
{{- define "asciiLoop" }}
	for i := 0; i < len(input); i++ {
		c := input[i]
		switch state {
{{ template "statesASCII" . }}
		default:
			return false
		}
	}
{{- end -}}
`

const utf8LoopTemplate = `
{{- define "utf8Loop" }}
	for i := 0; i < len(input); {
		// Invalid UTF-8 decodes as (RuneError, 1) and is matched as U+FFFD,
		// exactly like regexp: each bad byte is one U+FFFD rune.
		r, size := utf8.DecodeRuneInString(input[i:])
		switch state {
{{ template "statesRune" . }}
		default:
			return false
		}
		i += size
	}
{{- end -}}
`

// ---------- contains loops ----------

const asciiSearchLoopTemplate = `
{{- define "asciiSearchLoop" }}
	for i := 0; i < len(input); i++ {
{{- if .SkipToByte }}
		if state == {{ .Start }} {
			// The DFA can only leave the start state on {{ quoteByte .SkipByte }}: memchr to it.
			j := strings.IndexByte(input[i:], {{ quoteByte .SkipByte }})
			if j < 0 {
				return false
			}
			i += j
		}
{{- end }}
		c := input[i]
		switch state {
{{ template "statesASCIISearch" . }}
		default:
			{{ .RestartBody }}
		}
	}
{{- end -}}
`

const utf8SearchLoopTemplate = `
{{- define "utf8SearchLoop" }}
	for i := 0; i < len(input); {
		// Invalid UTF-8 decodes as (RuneError, 1) and is matched as U+FFFD,
		// exactly like regexp: each bad byte is one U+FFFD rune.
		r, size := utf8.DecodeRuneInString(input[i:])
		switch state {
{{ template "statesRuneSearch" . }}
		default:
			{{ .RestartBody }}
		}
		i += size
	}
{{- end -}}
`

// ---------- state switch cases ----------

// statesInner handles full/prefix; statesContainsInner handles contains.
// Byte vs rune condition and the no-match action are passed as parameters.

const statesTemplate = `
{{- define "statesASCII" }}{{ template "statesInner" (args . "byte" "return false") }}{{ end }}
{{- define "statesRune" }}{{ template "statesInner" (args . "rune" "return false") }}{{ end }}
{{- define "statesASCIISearch" }}{{ template "statesInner" (args . "byte" .RestartBody) }}{{ end }}
{{- define "statesRuneSearch" }}{{ template "statesInner" (args . "rune" .RestartBody) }}{{ end }}
{{- define "statesInner" -}}
{{- $ctx := index . 0 -}}
{{- $condKind := index . 1 -}}
{{- $noMatch := index . 2 -}}
{{- range $ctx.States }}{{ if isLive . }}
		case {{ .ID }}:
			switch {
{{- range groupTransitions $ctx $condKind . }}
			case {{ .Cond }}: {{ .Body }}
{{- end }}
			default: {{ $noMatch }}
			}
{{- end }}{{ end }}
{{- end -}}
`

// ---------- accept check ----------

const acceptCheckTemplate = `
{{- define "acceptCheck" -}}
{{- if eq (len .AcceptIDs) 0 }}
	return false
{{- else if eq (len .AcceptIDs) 1 }}
	return state == {{ index .AcceptIDs 0 }}
{{- else }}
	switch state {
	case {{ range $i, $id := .AcceptIDs }}{{ if $i }}, {{ end }}{{ $id }}{{ end }}:
		return true
	default:
		return false
	}
{{- end }}
{{- end -}}
`
