// Code generated by regex-gen. DO NOT EDIT.
// Source regex: `[A-Za-z_][A-Za-z0-9_]*`

package e2e


import "github.com/wow-look-at-my/go-regex-compiler/match"


// MatchIdentifier reports whether input fully matches the regex `[A-Za-z_][A-Za-z0-9_]*`.
func MatchIdentifier(input string) bool {
	state := 0
	for i := 0; i < len(input); i++ {
		c := input[i]
		switch state {

		case 0:
			switch {
			case match.InRange(c, 'A', 'Z'), c == '_', match.InRange(c, 'a', 'z'): state = 1
			default: return false
			}
		case 1:
			switch {
			case match.InRange(c, '0', '9'), match.InRange(c, 'A', 'Z'), c == '_', match.InRange(c, 'a', 'z'): state = 1
			default: return false
			}
		default:
			return false
		}
	}

	return state == 1
}
