// Code generated by regex-gen. DO NOT EDIT.
// Source regex: `(?i)hello`

package e2e



// MatchCaseInsensitive reports whether input fully matches the regex `(?i)hello`.
func MatchCaseInsensitive(input string) bool {
	state := 0
	for i := 0; i < len(input); i++ {
		c := input[i]
		switch state {

		case 0:
			switch {
			case c == 'H', c == 'h': state = 1
			default: return false
			}
		case 1:
			switch {
			case c == 'E', c == 'e': state = 2
			default: return false
			}
		case 2:
			switch {
			case c == 'L', c == 'l': state = 3
			default: return false
			}
		case 3:
			switch {
			case c == 'L', c == 'l': state = 4
			default: return false
			}
		case 4:
			switch {
			case c == 'O', c == 'o': state = 5
			default: return false
			}
		case 5:
			switch {
			default: return false
			}
		default:
			return false
		}
	}

	return state == 5
}
