// Code generated by regex-gen. DO NOT EDIT.
// Source regex: `(https?://)?[a-z]+\.[a-z]{2,}`

package e2e


import "github.com/wow-look-at-my/go-regex-compiler/match"


// MatchURL reports whether input fully matches the regex `(https?://)?[a-z]+\.[a-z]{2,}`.
func MatchURL(input string) bool {
	state := 0
	for i := 0; i < len(input); i++ {
		c := input[i]
		switch state {

		case 0:
			switch {
			case match.InRange(c, 'a', 'g'): state = 1
			case c == 'h': state = 2
			case match.InRange(c, 'i', 'z'): state = 1
			default: return false
			}
		case 1:
			switch {
			case c == '.': state = 3
			case match.InRange(c, 'a', 'z'): state = 1
			default: return false
			}
		case 2:
			switch {
			case c == '.': state = 3
			case match.InRange(c, 'a', 's'): state = 1
			case c == 't': state = 4
			case match.InRange(c, 'u', 'z'): state = 1
			default: return false
			}
		case 3:
			switch {
			case match.InRange(c, 'a', 'z'): state = 5
			default: return false
			}
		case 4:
			switch {
			case c == '.': state = 3
			case match.InRange(c, 'a', 's'): state = 1
			case c == 't': state = 6
			case match.InRange(c, 'u', 'z'): state = 1
			default: return false
			}
		case 5:
			switch {
			case match.InRange(c, 'a', 'z'): state = 7
			default: return false
			}
		case 6:
			switch {
			case c == '.': state = 3
			case match.InRange(c, 'a', 'o'): state = 1
			case c == 'p': state = 8
			case match.InRange(c, 'q', 'z'): state = 1
			default: return false
			}
		case 7:
			switch {
			case match.InRange(c, 'a', 'z'): state = 7
			default: return false
			}
		case 8:
			switch {
			case c == '.': state = 3
			case c == ':': state = 9
			case match.InRange(c, 'a', 'r'): state = 1
			case c == 's': state = 10
			case match.InRange(c, 't', 'z'): state = 1
			default: return false
			}
		case 9:
			switch {
			case c == '/': state = 11
			default: return false
			}
		case 10:
			switch {
			case c == '.': state = 3
			case c == ':': state = 9
			case match.InRange(c, 'a', 'z'): state = 1
			default: return false
			}
		case 11:
			switch {
			case c == '/': state = 12
			default: return false
			}
		case 12:
			switch {
			case match.InRange(c, 'a', 'z'): state = 1
			default: return false
			}
		default:
			return false
		}
	}

	return state == 7
}
