// Code generated by regex-gen. DO NOT EDIT.
// Source regex: `[a-z]+`

package e2e


import "github.com/wow-look-at-my/go-regex-compiler/match"


// MatchCharClass reports whether input fully matches the regex `[a-z]+`.
func MatchCharClass(input string) bool {
	state := 0
	for i := 0; i < len(input); i++ {
		c := input[i]
		switch state {

		case 0:
			switch {
			case match.InRange(c, 'a', 'z'): state = 1
			default: return false
			}
		case 1:
			switch {
			case match.InRange(c, 'a', 'z'): state = 1
			default: return false
			}
		default:
			return false
		}
	}

	return state == 1
}
